# These are supported funding model platforms

# GitHub Sponsors
# github: [hollowhouseinstitute]

# Open Collective
# open_collective: hollow-house-institute

# Patreon
# patreon: hollowhouseinstitute

# Custom funding links
# custom: ["https://hollowhouseinstitute.org/donate", "https://hollowhouseinstitute.org/support"]

# Note: Funding information will be added once sponsorship platforms are set up.
# For licensing and commercial use inquiries, please open an issue or contact via GitHub.
